Fix misleading error
When providing an invalid request key, sometimes you'd see this error:

```
/Users/beckel/code/recurly/v3/clients/ruby/lib/recurly/schema/request_caster.rb:46:in `block in cast': undefined method `type' for nil:NilClass (NoMethodError)
```

Now will see this:

```
/Users/beckel/code/recurly/v3/clients/ruby/lib/recurly/schema/schema_validator.rb:27:in
`block in validate!': Attribute 'shipping_address' does not exist on
request Recurly::Requests::AccountCreate. Did you mean
'shipping_addresses'? (ArgumentError)`
```